
DROP TABLE "BAJA";
DROP TABLE "EXAMEN_ANDROLOGICO";
DROP TABLE "DESTETE";
DROP TABLE "PARTO";
DROP TABLE "PALPACION";
DROP TABLE "CELO";
DROP TABLE "VACA";
DROP TABLE "BOVINO";
DROP TABLE "ESTADO_DESARROLLO";
DROP TABLE "MODO_PREÑEZ";
DROP TABLE "RAZA";
DROP TABLE "CONFIGURACION";
DROP TABLE "FINCA";

CREATE TABLE "FINCA"
(    
    "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),   
    "NOMBRE" VARCHAR(50),     
    "DIRECCION" VARCHAR(250),
    "AREA" DOUBLE,
    "CONTACTO" VARCHAR(250)
);

CREATE TABLE "CONFIGURACION"
(
    "ID" INT NOT NULL PRIMARY KEY
    GENERATED ALWAYS AS IDENTITY
    (START WITH 1, INCREMENT BY 1), 
    "ID_FINCA" INT,
    "MAX_IEP" INT,
    "ALERTA_PALPACION" INT,
    "ALERTA_PARTO" INT,
    "ALERTA_DESTETE" INT,
    CONSTRAINT CONFIGURACION_FINCA_FK FOREIGN KEY (ID_FINCA) REFERENCES FINCA(ID)
);

CREATE TABLE "ESTADO_DESARROLLO"
(    
    "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),  
    "ESTADO" VARCHAR(50)
);

CREATE TABLE "MODO_PREÑEZ"
(    
    "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),  
    "MODO" VARCHAR(50)
);

CREATE TABLE "RAZA"
(    
    "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),  
    "RAZA" VARCHAR(50)
);

CREATE TABLE "BOVINO"
(    
    "ID" INT NOT NULL PRIMARY KEY, 
    "NOMBRE" VARCHAR(50),
    "FECHA_NACIMIENTO" DATE,
    "CARACTERISTICAS" VARCHAR(250),
    "PESO" FLOAT,
    "ID_RAZA" INT,
    "ID_PADRE" INT,
    "ID_MADRE" INT,
    "ID_FINCA" INT,
    "ES_TORO" SMALLINT,
    CONSTRAINT BOVINO_PADRE_FK FOREIGN KEY (ID_PADRE) REFERENCES BOVINO(ID),
    CONSTRAINT BOVINO_MADRE_FK FOREIGN KEY (ID_MADRE) REFERENCES BOVINO(ID),
    CONSTRAINT FINCA_FK FOREIGN KEY (ID_FINCA) REFERENCES FINCA(ID),
    CONSTRAINT RAZA_FK FOREIGN KEY (ID_RAZA) REFERENCES RAZA(ID)
);

CREATE TABLE "VACA"
(    
    "ID_BOVINO" INT NOT NULL PRIMARY KEY,
    "ID_MODO_PREÑEZ" INT,
    "ID_ESTADO_DESARROLLO" INT,
    CONSTRAINT VACA_BOVINO_FK FOREIGN KEY (ID_BOVINO) REFERENCES BOVINO(ID),
    CONSTRAINT VACA_MODO_PREÑEZ_FK FOREIGN KEY (ID_MODO_PREÑEZ) REFERENCES MODO_PREÑEZ(ID),  
    CONSTRAINT VACA_ESTADO_DESARROLLO_FK FOREIGN KEY (ID_ESTADO_DESARROLLO) REFERENCES ESTADO_DESARROLLO(ID)
);

CREATE TABLE "BAJA"
(    
    "ID_BOVINO" INT NOT NULL PRIMARY KEY,  
    "FECHA" DATE,
    "CAUSA" VARCHAR(250),
    CONSTRAINT BAJA_BOVINO_FK FOREIGN KEY (ID_BOVINO) REFERENCES BOVINO(ID)
);

CREATE TABLE "PALPACION"
(    
    "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),  
    "ID_BOVINO" INT NOT NULL,  
    "FECHA" DATE,
    "CONDICION_CORPORAL" DOUBLE,
    "CONFIRMACION" VARCHAR(50),
    "RESULTADO" VARCHAR(250),
    CONSTRAINT PALPACION_BOVINO_FK FOREIGN KEY (ID_BOVINO) REFERENCES BOVINO(ID)
);

CREATE TABLE "PARTO"
(    
    "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    "ID_PADRE" INT NOT NULL,  
    "ID_MADRE" INT NOT NULL,
    "FECHA" DATE,
    "MUERTE_PREMATURA" SMALLINT,
    "SEXO" VARCHAR(50),
    CONSTRAINT PARTO_PADRE_FK FOREIGN KEY (ID_PADRE) REFERENCES BOVINO(ID),
    CONSTRAINT PARTO_MADRE_FK FOREIGN KEY (ID_MADRE) REFERENCES BOVINO(ID)
);

CREATE TABLE "CELO"
(    
    "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    "ID_BOVINO" INT NOT NULL,  
    "FECHA" DATE,
    CONSTRAINT CELO_BOVINO_FK FOREIGN KEY (ID_BOVINO) REFERENCES BOVINO(ID)
);

CREATE TABLE "DESTETE"
(    
    "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    "ID_BOVINO" INT NOT NULL,  
    "FECHA" DATE,
    CONSTRAINT DESTETE_BOVINO_FK FOREIGN KEY (ID_BOVINO) REFERENCES BOVINO(ID)
);

CREATE TABLE "EXAMEN_ANDROLOGICO"
(    
    "ID" INT NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    "ID_BOVINO" INT NOT NULL,  
    "FECHA" DATE,
    "CONDICION_CORPORAL" VARCHAR(250),
    "LIBIDO" SMALLINT,
    "CAPACIDAD_DE_MONTA" SMALLINT,
    "PREPUCIO" SMALLINT,
    "PENE" SMALLINT,
    "TESTICULOS" SMALLINT,
    "EPIDIDIMOS" SMALLINT,
    "GLANDULAS_BULBOURETRALES" SMALLINT,
    "PROSTATA" SMALLINT,
    "VESICULAS_SEMINALES" SMALLINT,
    "AMPULAS" SMALLINT,
    "DESCANSO" FLOAT,
    "CIRCUNFERENCIA_ESCROTAL" FLOAT,
    "VOLUMEN_EYACULADO" FLOAT,
    "CONCENTRACION" FLOAT,
    "MOTILIDAD_MASAL" FLOAT,
    "MOTILIDAD_PROGRESIVA" FLOAT,
    "MORFOLOGIA_NORMAL" FLOAT,
    "DANOS_ACROSOMALES" VARCHAR(50),
    "ANORMALIDADES_PRIMARIAS" VARCHAR(50),
    "ANORMALIDADES_SECUNDARIAS" VARCHAR(50),
    "ANORMALIDAD_FRECUENTE" VARCHAR(50),
    "TOTAL_ANORMALIDADES" FLOAT,
    "LEUCOCITOS" FLOAT,
    "CELULAS_EPITELIALES" FLOAT,
    "PALPACION" SMALLINT,
    "ECOGRAFIA" SMALLINT,
    "VAGINA_ARTIFICIAL" SMALLINT,
    "ELECTROEYACULADOR" SMALLINT,
    "PROTUSION" SMALLINT,
    "SATISFACTORIO" SMALLINT,
    "VETERINARIO" VARCHAR(250),
    "OBSERVACIONES" VARCHAR(250),
    CONSTRAINT EXAMEN_ANDROLOGICO_BOVINO_FK FOREIGN KEY (ID_BOVINO) REFERENCES BOVINO(ID)
);

/* 
Agrega a la DB los datos iniciales para Estado de Desarrollo, Raza y Modo preñez.
 */
INSERT INTO estado_desarrollo (estado)
VALUES  ('Ternera'),
	('Novilla'),
	('Vaca');

INSERT INTO raza (raza)
VALUES	('Desconocida'),
        ('Angus'),
        ('Ayrshire'),
        ('Blonde D’Aquitaine'),
        ('Brahman'),
        ('Brangus'),
        ('Charbray'),
        ('Charolaise'),
        ('Chumeca'),
        ('Guernsey'),
        ('Guzerat'),
        ('Gyr'),
        ('Gyrolando'),
        ('Holstein Rojo'),
        ('Holstein'),
        ('Jersey'),
        ('Limousine'),
        ('Nelore'),
        ('Pardo Suizo'),
        ('Senepol'),
        ('Simbrah'),
        ('Simmental'),
        ('Sueco Rojo'),
        ('Wagyu');

INSERT INTO modo_preñez (modo)
VALUES  ('No preñada'),
	('Transferencia de embriones'),
	('Monto natural'),
	('IA TD'),
	('IA');
