/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.ecci.Frames;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static org.apache.commons.lang3.CharSetUtils.delete;
import ucr.ac.cr.ecci.Models.Finca;
import ucr.ac.cr.ecci.DBManager;
import static ucr.ac.cr.ecci.Frames.VacaTableUI.centreWindow;
import ucr.ac.cr.ecci.Models.Configuracion;

/**
 *
 * @author afg
 */
public class FincaUI extends javax.swing.JFrame {
    
    Finca finca;
    boolean nueva;
    Configuracion conf;

    /**
     * Creates new form FincaUI
     */
    public FincaUI() {
        nueva = true;
        centreWindow(this);
        initComponents();
        editarCheckBox.setVisible(false);
        eliminarButton.setVisible(false);
    }
    
    public FincaUI(Finca f) {
        nueva = false;
        finca = f;
        centreWindow(this);
        initComponents();
        setEnabledFalse();
        nombreTextField.setText(finca.getNombre());
        if (finca.getArea() != null){
            areaFormattedTextField.setText(Double.toString(finca.getArea()));
        }
        contactoTextField.setText(finca.getContacto());
        direccionTextArea.setText(finca.getDireccion());
    }
    
    private void setEnabledFalse() {
        nombreTextField.setEditable(false);
        areaFormattedTextField.setEditable(false);
        contactoTextField.setEditable(false);
        direccionTextArea.setEditable(false);
        guardarButton.setVisible(false);
        eliminarButton.setVisible(false);

    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        TCUGanaderosPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("TCUGanaderosPU").createEntityManager();
        fincaQuery = java.beans.Beans.isDesignTime() ? null : TCUGanaderosPUEntityManager.createQuery("SELECT f FROM Finca f");
        fincaList = java.beans.Beans.isDesignTime() ? java.util.Collections.emptyList() : fincaQuery.getResultList();
        jMenuItem1 = new javax.swing.JMenuItem();
        eliminarButton = new javax.swing.JButton();
        guardarButton = new javax.swing.JButton();
        volverButton = new javax.swing.JButton();
        nombreLabel = new javax.swing.JLabel();
        nombreLabel1 = new javax.swing.JLabel();
        direccionLabel = new javax.swing.JLabel();
        areaLabel = new javax.swing.JLabel();
        contactoLabel = new javax.swing.JLabel();
        mLabel = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        direccionTextArea = new javax.swing.JTextArea();
        areaFormattedTextField = new javax.swing.JFormattedTextField();
        contactoTextField = new javax.swing.JTextField();
        editarCheckBox = new javax.swing.JCheckBox();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 100), new java.awt.Dimension(0, 100), new java.awt.Dimension(32767, 100));

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        guardarButton.setText("Guardar");
        guardarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarButtonActionPerformed(evt);
            }
        });

        volverButton.setText("Volver");
        volverButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverButtonActionPerformed(evt);
            }
        });

        nombreLabel.setText("Nombre:");

        direccionLabel.setText("Dirección:");

        areaLabel.setText("Área:");

        contactoLabel.setText("Contacto:");

        mLabel.setText("hectáreas");

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, new javax.swing.JComboBox(), org.jdesktop.beansbinding.ELProperty.create("${selectedItem.nombre}"), nombreTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        nombreTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreTextFieldActionPerformed(evt);
            }
        });

        direccionTextArea.setColumns(20);
        direccionTextArea.setLineWrap(true);
        direccionTextArea.setRows(5);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, new javax.swing.JComboBox(), org.jdesktop.beansbinding.ELProperty.create("${selectedItem.direccion}"), direccionTextArea, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        jScrollPane1.setViewportView(direccionTextArea);

        areaFormattedTextField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.###"))));

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, new javax.swing.JComboBox(), org.jdesktop.beansbinding.ELProperty.create("${selectedItem.area}"), areaFormattedTextField, org.jdesktop.beansbinding.BeanProperty.create("value"));
        bindingGroup.addBinding(binding);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, new javax.swing.JComboBox(), org.jdesktop.beansbinding.ELProperty.create("${selectedItem.contacto}"), contactoTextField, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        contactoTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactoTextFieldActionPerformed(evt);
            }
        });

        editarCheckBox.setText("Editar");
        editarCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                editarCheckBoxStateChanged(evt);
            }
        });
        editarCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarCheckBoxActionPerformed(evt);
            }
        });
        editarCheckBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                editarCheckBoxPropertyChange(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(volverButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eliminarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(guardarButton))
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(nombreLabel)
                                    .addComponent(contactoLabel))
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(areaLabel)
                                        .addGap(10, 10, 10)
                                        .addComponent(areaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4)
                                        .addComponent(mLabel))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(contactoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(editarCheckBox))))
                            .addComponent(direccionLabel))))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(nombreLabel)
                        .addGap(14, 14, 14)
                        .addComponent(contactoLabel)
                        .addGap(27, 27, 27)
                        .addComponent(direccionLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(areaFormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(3, 3, 3)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(areaLabel)
                                            .addComponent(mLabel))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(editarCheckBox))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nombreTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(contactoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(volverButton)
                    .addComponent(eliminarButton)
                    .addComponent(guardarButton))
                .addContainerGap())
        );

        bindingGroup.bind();

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void guardarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarButtonActionPerformed
        DBManager dbm = new DBManager();
        if (nueva){
            if (!nombreTextField.getText().equals("")){
                finca = new Finca();
                finca.setNombre(nombreTextField.getText());
                finca.setDireccion(direccionTextArea.getText());
                if (!areaFormattedTextField.getText().equals("")){
                    finca.setArea(Double.valueOf(areaFormattedTextField.getText()));
                }
                finca.setContacto(contactoTextField.getText());
                dbm.insert(finca);
                conf = new Configuracion();
                conf.setAlertaDestete(200);
                conf.setMaxAlertaDestete(240);
                conf.setAlertaPalpacion(15);
                conf.setMaxAlertaPalpacion(22);
                conf.setAlertaParto(260);
                conf.setIdFinca(finca);
                conf.setMaxIep(400);
                conf.setLimitePa(140);
                conf.setLimiteSc(1.8);
                dbm.insert(conf);
                dbm.close();
                dispose();  
            }
            else {
                JOptionPane.showMessageDialog(new JFrame(),"Debe incluir al menos el nombre.","Error de operación",JOptionPane.ERROR_MESSAGE);
            }
            
        } else {
            if (!nombreTextField.getText().equals("")){
                Finca f = dbm.findFincaById(finca.getId());
                f.setNombre(nombreTextField.getText());
                f.setDireccion(direccionTextArea.getText());
                if (!areaFormattedTextField.getText().equals("")){
                    f.setArea(Double.valueOf(areaFormattedTextField.getText()));
                }
                f.setContacto(contactoTextField.getText());
                dbm.updateFinca(f);
                dbm.close();
                dispose();        
            }
            else {
                JOptionPane.showMessageDialog(new JFrame(),"Debe incluir al menos el nombre.","Error de operación",JOptionPane.ERROR_MESSAGE);
            }
        } 
    }//GEN-LAST:event_guardarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed
        int des = JOptionPane.showConfirmDialog(null, "Está seguro que quiere eliminar esta Finca? La acción no es reversible.","Eliminar Finca", JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
        if (des == 0){
//            try {
                DBManager dbm = new DBManager();
                Finca f = dbm.findFincaById(finca.getId());
                Configuracion c = dbm.findConfiguracionById(finca.getId());
                if (c != null)
                    dbm.delete(c);
                dbm.delete(f);
                dbm.close();
                dispose();    
//            } catch (Exception e) {
//                JOptionPane.showMessageDialog(new JFrame(),"Esta Finca está asociada a uno o más Bovinos.","Error de operación",JOptionPane.ERROR_MESSAGE);
//            }         
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    private void volverButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverButtonActionPerformed
            setVisible(false);
            dispose();  
    }//GEN-LAST:event_volverButtonActionPerformed

    private void nombreTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreTextFieldActionPerformed

    private void contactoTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactoTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contactoTextFieldActionPerformed

    private void editarCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_editarCheckBoxStateChanged
        if (editarCheckBox.isSelected()){
            areaFormattedTextField.setEditable(true);
            nombreTextField.setEditable(true);
            contactoTextField.setEditable(true);
            direccionTextArea.setEditable(true);
            guardarButton.setVisible(true);
            eliminarButton.setVisible(true);
        } else if (!editarCheckBox.isSelected()){
            setEnabledFalse();
        }
    }//GEN-LAST:event_editarCheckBoxStateChanged

    private void editarCheckBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_editarCheckBoxPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_editarCheckBoxPropertyChange

    private void editarCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_editarCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FincaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FincaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FincaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FincaUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FincaUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.persistence.EntityManager TCUGanaderosPUEntityManager;
    private javax.swing.JFormattedTextField areaFormattedTextField;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JLabel contactoLabel;
    private javax.swing.JTextField contactoTextField;
    private javax.swing.JLabel direccionLabel;
    private javax.swing.JTextArea direccionTextArea;
    private javax.swing.JCheckBox editarCheckBox;
    private javax.swing.JButton eliminarButton;
    private javax.swing.Box.Filler filler1;
    private java.util.List<ucr.ac.cr.ecci.Models.Finca> fincaList;
    private javax.persistence.Query fincaQuery;
    private javax.swing.JButton guardarButton;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mLabel;
    private javax.swing.JLabel nombreLabel;
    private javax.swing.JLabel nombreLabel1;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JButton volverButton;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

}
