/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ucr.ac.cr.ecci.Frames;

import java.sql.SQLException;
import javafx.scene.control.CheckBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import ucr.ac.cr.ecci.DBManager;
import static ucr.ac.cr.ecci.Frames.VacaTableUI.centreWindow;
import ucr.ac.cr.ecci.Models.EstadoDesarrollo;
import ucr.ac.cr.ecci.Models.ModoPreñez;
import ucr.ac.cr.ecci.Models.Raza;

/**
 *
 * @author afg
 */
public class TCUGanaderosUI extends javax.swing.JFrame {

     private final javax.persistence.EntityManager TCUGanaderosPUEntityManager;
    
    /**
     * Creates new form TCUGanaderosUI
     */
    public TCUGanaderosUI() {
        TCUGanaderosPUEntityManager = java.beans.Beans.isDesignTime() ? null : javax.persistence.Persistence.createEntityManagerFactory("TCUGanaderosPU").createEntityManager();
        centreWindow(this);
        initComponents();
        seeder();
    }
    
    void seeder(){
        DBManager dbm = new DBManager();
        String raza_query = "SELECT r FROM Raza r";
        javax.persistence.Query razaQuery = TCUGanaderosPUEntityManager.createQuery(raza_query);
        java.util.List<ucr.ac.cr.ecci.Models.Raza> razaList = razaQuery.getResultList();
        if (razaList.isEmpty()){
            String[] razas_array = {"Desconocida","Angus","Ayrshire","Blonde D’Aquitaine",
            "Brahman","Brangus","Charbray","Charolaise","Chumeca","Guernsey",
            "Guzerat","Gyr","Gyrolando","Holstein Rojo","Holstein","Jersey",
            "Limousine","Nelore","Pardo Suizo","Senepol","Simbrah","Simmental",
            "Sueco Rojo","Wagyu"};
            for (String r : razas_array) {
                Raza raza = new Raza();
                raza.setRaza(r);
                dbm.insert(raza);
            }
        }
        String estado_query = "SELECT e FROM EstadoDesarrollo e";
        javax.persistence.Query estadoQuery = TCUGanaderosPUEntityManager.createQuery(estado_query);
        java.util.List<ucr.ac.cr.ecci.Models.EstadoDesarrollo> estadoList = estadoQuery.getResultList();
        if (estadoList.isEmpty()){
            String[] estados_array = {"Ternera", "Novilla","Vaca"};
            for (String e : estados_array) {
                EstadoDesarrollo estado = new EstadoDesarrollo();
                estado.setEstado(e);
                dbm.insert(estado);
            }
        }
        String modo_query = "SELECT m FROM ModoPreñez m";
        javax.persistence.Query modoQuery = TCUGanaderosPUEntityManager.createQuery(modo_query);
        java.util.List<ucr.ac.cr.ecci.Models.ModoPreñez> modoList = modoQuery.getResultList();
        if (modoList.isEmpty()){
            String[] modos_array = {"No preñada", "Transferencia de embriones","Monto natural", "IATF", "IA"};
            for (String m : modos_array) {
                ModoPreñez modo = new ModoPreñez();
                modo.setModo(m);
                dbm.insert(modo);
            }
        }
        dbm.close(); 
    }
    
    private boolean hayFincas() {
        // Revisa si ya existe una finca, si no tira alerta
        String finca_query = "SELECT F FROM Finca f";
        javax.persistence.Query fincaCheckQuery = TCUGanaderosPUEntityManager.createQuery(finca_query);
        java.util.List<ucr.ac.cr.ecci.Models.Raza> fincaCheckList = fincaCheckQuery.getResultList();
        if (fincaCheckList.isEmpty()){
            return false;
        } else return true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fincasButton = new javax.swing.JButton();
        vacasButton = new javax.swing.JButton();
        torosButton = new javax.swing.JButton();
        resumenButton = new javax.swing.JButton();
        configuracionesButton = new javax.swing.JButton();
        alertasButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        ayudaMenu = new javax.swing.JMenu();
        acercaMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        fincasButton.setText("Fincas");
        fincasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fincasButtonActionPerformed(evt);
            }
        });

        vacasButton.setText("Vacas");
        vacasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vacasButtonActionPerformed(evt);
            }
        });

        torosButton.setText("Toros");
        torosButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                torosButtonActionPerformed(evt);
            }
        });

        resumenButton.setText("Resumen");
        resumenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resumenButtonActionPerformed(evt);
            }
        });

        configuracionesButton.setText("Configuración");
        configuracionesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configuracionesButtonActionPerformed(evt);
            }
        });

        alertasButton.setText("Alertas");
        alertasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alertasButtonActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/images/Gestion_Bovina.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        ayudaMenu.setText("Ayuda");

        acercaMenuItem.setText("Acerca de la aplicación");
        acercaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acercaMenuItemActionPerformed(evt);
            }
        });
        ayudaMenu.add(acercaMenuItem);

        jMenuBar1.add(ayudaMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fincasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vacasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(torosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(resumenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(configuracionesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alertasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(fincasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(vacasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(torosButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(resumenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(configuracionesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(alertasButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fincasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fincasButtonActionPerformed
        FincaTableUI finca = new FincaTableUI();
        finca.setLocationRelativeTo(null);
        finca.setVisible(true);
    }//GEN-LAST:event_fincasButtonActionPerformed

    private void vacasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vacasButtonActionPerformed
        if (!hayFincas()){
            JOptionPane.showMessageDialog(null, "Debe haber al menos una finca antes de agregar bovinos."); 
        }else{
            VacaTableUI vaca = new VacaTableUI();
            vaca.setLocationRelativeTo(null);
            vaca.setVisible(true);
        }
    }//GEN-LAST:event_vacasButtonActionPerformed

    private void torosButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_torosButtonActionPerformed
        if (!hayFincas()){
            JOptionPane.showMessageDialog(null, "Debe haber al menos una finca antes de agregar bovinos."); 
        }else{
            ToroTableUI toro = new ToroTableUI();
            toro.setLocationRelativeTo(null);
            toro.setVisible(true);
        }
    }//GEN-LAST:event_torosButtonActionPerformed

    private void configuracionesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configuracionesButtonActionPerformed
        ConfiguracionUI config = new ConfiguracionUI();
        config.setLocationRelativeTo(null);
        config.setVisible(true);
    }//GEN-LAST:event_configuracionesButtonActionPerformed

    private void alertasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alertasButtonActionPerformed
        AlertasUI alerta = new AlertasUI();
        alerta.setLocationRelativeTo(null);
        alerta.setVisible(true);
    }//GEN-LAST:event_alertasButtonActionPerformed

    private void resumenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resumenButtonActionPerformed
        ResumenUI resumen =  new ResumenUI();
        resumen.setLocationRelativeTo(null);
        resumen.setVisible(true);
    }//GEN-LAST:event_resumenButtonActionPerformed

    private void acercaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acercaMenuItemActionPerformed
        AcercaUI acerca= new AcercaUI();
        acerca.setLocationRelativeTo(null);
        acerca.setVisible(true);
    }//GEN-LAST:event_acercaMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws SQLException, ClassNotFoundException {
        

        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TCUGanaderosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TCUGanaderosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TCUGanaderosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TCUGanaderosUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TCUGanaderosUI().setVisible(true);
            }
        });
    }
    
    /*
     * The method creates a Connection object. Loads the embedded driver,
     * starts and connects to the database using the connection URL.
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem acercaMenuItem;
    private javax.swing.JButton alertasButton;
    private javax.swing.JMenu ayudaMenu;
    private javax.swing.JButton configuracionesButton;
    private javax.swing.JButton fincasButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton resumenButton;
    private javax.swing.JButton torosButton;
    private javax.swing.JButton vacasButton;
    // End of variables declaration//GEN-END:variables
}
